# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Common configuration for all VMs
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  
    # Web server VMs
    config.vm.define "web01" do |web01|
      web01.vm.box = "ubuntu/bionic64"
      web01.vm.network "private_network", ip: "192.168.56.41"
      web01.vm.hostname = "web01"
    end
  
    config.vm.define "web02" do |web02|
      web02.vm.box = "ubuntu/bionic64"
      web02.vm.network "private_network",  ip: "192.168.56.42"
      web02.vm.hostname = "web02"
    end
  
    # Database server VM
    config.vm.define "db01" do |db01|
      db01.vm.box = "centos/7"
      db01.vm.network "private_network",  ip: "192.168.56.43"
      db01.vm.hostname = "db01"
  
      # Provisioning script for db01
      db01.vm.provision "shell", inline: <<-SHELL
        # Update package index
        yum install -y  wget unzip mariadb-server -y
        systemctl start mariadb
        systemctl enable mariadb
  
        # Install necessary software (e.g., MySQL, PostgreSQL, etc.)
        # Add your provisioning steps here
      SHELL
    end
  end
  